FROM maven:3.8.6-openjdk-17 AS builder
WORKDIR /workspace/app
COPY Backend-CICD/pom.xml .
COPY Backend-CICD/src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
RUN addgroup --system spring && adduser --system spring --ingroup spring
USER spring:spring
COPY --from=builder /workspace/app/target/*.jar app.jar
EXPOSE 5050
ENTRYPOINT ["java", "-jar", "/app/app.jar"]