# Simple one-stage build
FROM maven:3.8.5-openjdk-17 AS builder
WORKDIR /workspace/app

# Copy entire backend project
COPY ../Backend-CICD/ .

# Build the application
RUN mvn clean package -DskipTests

# Runtime image
FROM openjdk:17
WORKDIR /app
COPY --from=builder /workspace/app/target/*.jar app.jar

EXPOSE 5050
ENTRYPOINT ["java", "-jar", "app.jar"]