# Build stage
FROM node:18-alpine AS builder
WORKDIR /app

# Copy entire frontend project
COPY ../Frontend-CICD/ ./

# Install and build
RUN npm install
RUN npm run build

# Run stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]