version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cicd-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cicdproject
      MYSQL_ROOT_PASSWORD: Kedharnath@9381
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - cicd-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cicd-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cicdproject?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Kedharnath@9381
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 5050
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:5050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cicd-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cicd-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cicd-network

volumes:
  mysql_data:

networks:
  cicd-network:
    driver: bridge