version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cicd-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cicdproject
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - cicd-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cicd-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cicdproject?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 5050
    depends_on:
      - db
    ports:
      - "5050:5050"
    networks:
      - cicd-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cicd-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cicd-network

volumes:
  mysql_data:

networks:
  cicd-network:
    driver: bridge