name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  verify-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Verify project structure
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo "=== Backend Contents ==="
          ls -la Backend-CICD/
          echo "=== Frontend Contents ==="
          ls -la Frontend-CICD/
          echo "=== Docker Files ==="
          ls -la docker-git-fullstackapp/

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build and Test Backend
        run: |
          cd Backend-CICD
          mvn clean test -DskipTests=false

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend-CICD/package-lock.json
          
      - name: Install and Build Frontend
        run: |
          cd Frontend-CICD
          npm ci
          npm run build

  validate-docker:
    runs-on: ubuntu-latest
    needs: [test-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Docker configurations
        run: |
          cd docker-git-fullstackapp
          docker-compose config
          echo "✅ Docker configurations are valid"