name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check project structure
        run: |
          echo "=== Root directory ==="
          ls -la
          echo "=== docker-git-fullstackapp contents ==="
          ls -la docker-git-fullstackapp/
          echo "=== Backend-CICD contents ==="
          ls -la Backend-CICD/
          echo "=== Frontend-CICD contents ==="
          ls -la Frontend-CICD/

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build and Test Backend
        run: |
          cd Backend-CICD
          mvn clean test -DskipTests=false

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install and Build Frontend
        run: |
          cd Frontend-CICD
          npm ci
          npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: [test-backend, build-frontend]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build backend Docker image
        run: |
          cd docker-git-fullstackapp
          docker build -f Dockerfile.backend -t cicd-backend ..

      - name: Build frontend Docker image
        run: |
          cd docker-git-fullstackapp
          docker build -f Dockerfile.frontend -t cicd-frontend ..

  docker-compose-test:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - uses: actions/checkout@v4
      
      - name: Test with Docker Compose
        run: |
          cd docker-git-fullstackapp
          docker-compose up -d
          sleep 30
          docker-compose ps
          docker-compose logs
          docker-compose down